# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  placesdb:
    container_name: places-app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8082:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password.123
    networks:
      - placesnet
  places:
    container_name: places-app
    image: places
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on: 
      - placesdb
    environment:
      - DB_HOST=placesdb
      - DB_NAME=PlacesApp
      - DB_MSSQL_SA_PASSWORD=Password.123
    networks:
      - placesnet
    network_mode: host

networks:
  placesnet:
    driver: bridge
